quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.resteasy-reactive.json.default-charset=UTF-8
quarkus.package.type=fast-jar


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://db:5432/product_db}
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true


quarkus.hibernate-orm.database.generation=update
quarkus.http.cors=true

quarkus.log.level=INFO
quarkus.log.category."io.smallrye.jwt".level=DEBUG

########################################
# JWT SIGNING (PRIVATE KEY)
########################################
# Absolute or relative path to private PEM
#smallrye.jwt.sign.key.location=keys/privateKey.pem

# Algorithm used to sign tokens
smallrye.jwt.sign.algorithm=RS256

########################################
# JWT VERIFICATION (PUBLIC KEY)
########################################
# Public key used to verify incoming tokens
# JWT
mp.jwt.verify.publickey.location=/deployments/keys/publicKey.pem
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
smallrye.jwt.sign.key.location=/deployments/keys/privateKey.pem

########################################
# JWT GENERAL SETTINGS
########################################
# Optional but recommended
mp.jwt.verify.audiences=quarkus-api

########################################
# Security (optional defaults)
########################################
quarkus.security.auth.enabled=true

###########################
# METRICS
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Exponer endpoint
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm.enabled=true

# Path de métricas
quarkus.micrometer.export.prometheus.path=/q/metrics
###############
# KAFKA
################
# Kafka bootstrap
# Kafka bootstrap server
kafka.bootstrap.servers=kafka:9092

# Producer
mp.messaging.outgoing.my-out.connector=smallrye-kafka
mp.messaging.outgoing.my-out.topic=my-cart-topic
mp.messaging.outgoing.my-out.bootstrap.servers=kafka:9092
mp.messaging.outgoing.my-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
mp.messaging.incoming.my-in.connector=smallrye-kafka
mp.messaging.incoming.my-in.topic=my-user-topic
mp.messaging.incoming.my-in.bootstrap.servers=kafka:9092
mp.messaging.incoming.my-in.value.deserializer=com.kafka.common.serialization.UserCreatedEventDeserializer
mp.messaging.incoming.my-in.auto.offset.reset=earliest

mp.messaging.incoming.my-in.group.id=my-group-product


quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

#mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=auth-service

quarkus.redis.hosts=redis://redis:6379
##SWAGGER##
#%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.always-include=true

