quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.resteasy-reactive.json.default-charset=UTF-8
quarkus.package.type=fast-jar



quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/products_db}
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true


quarkus.http.cors=true

quarkus.log.level=INFO
quarkus.log.category."io.smallrye.jwt".level=DEBUG
###############################
### RABBITMQ
###############################3
##mp.messaging.connector.smallrye-rabbitmq.host=rabbitmq

mp.messaging.outgoing.product-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.product-events-out.exchange.name=product-exchange
mp.messaging.outgoing.product-events-out.routing-key=product.created

mp.messaging.incoming.product-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.product-events-in.queue.name=product-queue
mp.messaging.incoming.product-events-in.exchange.name=product-exchange
mp.messaging.incoming.product-events-in.exchange.type=topic

# Use DevServices (auto RabbitMQ)
%test.quarkus.rabbitmq.devservices.enabled=false

# =========================================
# GLOBAL RABBITMQ CONFIG
# =========================================
rabbitmq-host=rabbitmq
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

%test.rabbitmq-host=localhost
%test.rabbitmq-port=5672
%test.rabbitmq-username=guest
%test.rabbitmq-password=guest

# Incoming
%test.mp.messaging.incoming.product-events-in-test.connector=smallrye-rabbitmq
#%test.mp.messaging.incoming.product-events-in-test.host=localhost
#%test.mp.messaging.incoming.product-events-in-test.port=5672
#%test.mp.messaging.incoming.product-events-in-test.username=guest
#%test.mp.messaging.incoming.product-events-in-test.password=guest
%test.mp.messaging.incoming.product-events-in-test.queue.name=product-queue
%test.mp.messaging.incoming.product-events-in-test.exchange.name=product-exchange
%test.mp.messaging.incoming.product-events-in-test.exchange.type=topic
%test.mp.messaging.incoming.product-events-in-test.routing-keys=product.created

# Outgoing
%test.mp.messaging.outgoing.product-events-out-test.connector=smallrye-rabbitmq
#%test.mp.messaging.outgoing.product-events-out-test.host=localhost
#%test.mp.messaging.outgoing.product-events-out-test.port=5672
#%test.mp.messaging.outgoing.product-events-out-test.username=guest
%test.mp.messaging.outgoing.product-events-out-test.password=guest
%test.mp.messaging.outgoing.product-events-out-test.exchange.name=product-exchange
%test.mp.messaging.outgoing.product-events-out-test.exchange.type=topic
%test.mp.messaging.outgoing.product-events-out-test.default-routing-key=product.created



#testcontainers.reuse.enable=true


quarkus.kafka.devservices.enabled=false
########################################
# JWT SIGNING (PRIVATE KEY)
########################################
# Absolute or relative path to private PEM
#smallrye.jwt.sign.key.location=keys/privateKey.pem

# Algorithm used to sign tokens
#smallrye.jwt.sign.algorithm=RS256

########################################
# JWT VERIFICATION (PUBLIC KEY)
########################################
# Public key used to verify incoming tokens
# JWT
#mp.jwt.verify.publickey.location=/deployments/keys/publicKey.pem
#quarkus.log.category."io.smallrye.jwt".level=DEBUG
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#smallrye.jwt.sign.key.location=/deployments/keys/privateKey.pem


########################################
# JWT GENERAL SETTINGS
########################################
# Optional but recommended
mp.jwt.verify.audiences=quarkus-api

########################################
# Security (optional defaults)
########################################
quarkus.security.auth.enabled=true

###########################
# METRICS
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Exponer endpoint
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm.enabled=true

# Path de métricas
quarkus.micrometer.export.prometheus.path=/q/metrics
###############
# KAFKA
################
# Kafka bootstrap

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

#mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=auth-service

quarkus.redis.hosts=redis://redis:6379

##SWAGGER##
#%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.always-include=true

# Enable Swagger UI
quarkus.swagger-ui.always-include=true

# Custom path
quarkus.swagger-ui.path=/swagger

# Theme (optional)
quarkus.swagger-ui.theme=flattop

# Show request duration
quarkus.swagger-ui.display-request-duration=true

# Show operation IDs
quarkus.swagger-ui.display-operation-id=true
quarkus.swagger-ui.always-include=true




